### Sign in

POST http://localhost:5000/auth/signin
Content-Type: application/json

{
  "email": "test3@test.test",
  "password": "qwerty123"
}


### Sign up

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "test3@test.test",
  "password": "qwerty123",
  "firstName": "Mark",
  "lastName": "Mark",
  "nickname": "Mark"
}

### Sign out

POST http://localhost:5000/auth/signout
Content-Type: application/json

###

