### Create candidate for voting

POST http://localhost:5000/candidates
Content-Type: application/json

{
  "votingId": "5bcc764672eeb941e571ec1e",
  "name": "Diana",
  "description": "Diana candidate"
}

### Create candidates (many) for voting

POST http://localhost:5000/candidates/many
Content-Type: application/json

{
  "candidates": [{
    "votingId": "5bcc764672eeb941e571ec1e",
    "name": "Diana 1",
    "description": "Diana candidate"
  }, {
    "votingId": "5bcc764672eeb941e571ec1e",
    "name": "Diana 2",
    "description": "Diana candidate"
  }, {
    "votingId": "5bcc764672eeb941e571ec1e",
    "name": "Diana 3",
    "description": "Diana candidate"}
  ]
}


### Get candidate

GET http://localhost:5000/candidates/6bc9e03b80c69b470655012a

### Delete candidate

DELETE http://localhost:5000/candidates/5bc9e03b80c69b470655012a

### Update candidate

PUT http://localhost:5000/candidates/5bc9db6c84f54c411dc4c6fa
Content-Type: application/json

{
  "name": "Anna S",
  "description": "pending"
}

###
