### Create group

POST http://localhost:5000/groups
Content-Type: application/json

{
  "name": "Test1",
  "adminEmail": "test1@test.test",
  "membersEmails": ["test2@test.test", "test3@test.test"]
}

###
