### Create group

POST http://localhost:5000/api/groups
Content-Type: application/json

{
  "name": "Test1",
  "adminEmail": "test1@test.test",
  "membersEmails": ["test2@test.test", "test3@test.test"]
}


### Get votings by state

GET http://localhost:5000/api/groups/5bcc4ccb09ee131efeac922e/users/5bc8a8599c3d232278530a47/votings?state=recent

### Get users in group

GET http://localhost:5000/api/groups/5bc8a83e9c3d232278530a46/users
