### Create voting, voting candidates and coefficients

POST http://localhost:5000/api/votings
Content-Type: application/json

{
  "topic": "Go to Bali?)",
  "groupId": "5bcc4ccb09ee131efeac922e",
  "creatorId": "5bc8a8649c3d232278530a48",
  "dateStart": "Fri Oct 19 2018 19:27:28",
  "dateEnd": "Sun Nov 25 2018 10:00:00",
  "votersPercent": 50,
  "coefficients": [{"_id": 1, "name": "Coeff 1", "question": "Coeff question", "cost": 50},
    {"_id": 2, "name": "Coeff 2", "question": "Coeff question", "cost": 25},
    {"_id": 3, "name": "Coeff 2", "question": "Coeff question", "cost": 25}]
}

### Get voting

GET http://localhost:5000/api/votings/5bc9da58de27d540947ffa0a

### Get last votings

GET http://localhost:5000/api/votings/recent/5bf2918d77167f22f6f3471e

### Delete voting

DELETE http://localhost:5000/api/votings/5bc9e5560449594aa9c197f3

### Update voting

PUT http://localhost:5000/api/votings/5bc9da8fde27d540947ffa0b
Content-Type: application/json

{
  "topic": "Test voting 1",
  "status": "pending",
  "votersPercent": 70
}

### Get voting candidates

GET http://localhost:5000/api/votings/5bf152a50313505fd97aa304/candidates

### Vote

POST http://localhost:5000/api/votings/5bf152a50313505fd97aa304/vote
Content-Type: application/json

{
  "userId": "5bc8a8649c3d232278530a48",
  "candidateId": "5bf152c30313505fd97aa305",
  "coefficientValues": [{"_id": 1, "value": 25}, {"_id": 2, "value": 45}, {"_id": 3, "value": 14}]
}

### Get voting results

GET http://localhost:5000/api/votings/5bcc764672eeb941e571ec1e/results

### Check user can vote

GET http://localhost:5000/api/votings/5bcc764672eeb941e571ec1e/users/5bcc764672eeb941e571ec1e

###



