export const GET_NEW_VOTINGS_INIT = 'GET_NEW_VOTINGS_INIT';
export const GET_NEW_VOTINGS_SUCCESS = 'GET_NEW_VOTINGS_SUCCESS';
export const GET_NEW_VOTINGS_ERROR = 'GET_NEW_VOTINGS_ERROR';

export const GET_RECENT_VOTINGS_INIT = 'GET_RECENT_VOTINGS_INIT';
export const GET_RECENT_VOTINGS_SUCCESS = 'GET_RECENT_VOTINGS_SUCCESS';
export const GET_RECENT_VOTINGS_ERROR = 'GET_RECENT_VOTINGS_ERROR';
