export const ADD_VOTING_INIT = 'ADD_VOTING_INIT';
export const ADD_VOTING_SUCCESS = 'ADD_VOTING_SUCCESS';
export const ADD_VOTING_ERROR = 'ADD_VOTING_ERROR';

export const ADD_CANDIDATES_INIT = 'ADD_CANDIDATES_INIT';
export const ADD_CANDIDATES_SUCCESS = 'ADD_CANDIDATES_SUCCESS';
export const ADD_CANDIDATES_ERROR = 'ADD_CONDIDATES_ERROR';
