export const GET_ONE_VOTING_INIT = 'GET_ONE_VOTING_INIT';
export const GET_ONE_VOTING_SUCCESS = 'GET_ONE_VOTING_SUCCESS';
export const GET_ONE_VOTING_ERROR = 'GET_ONE_VOTING_ERROR';

export const GET_VOTING_CANDIDATES_INIT = 'GET_VOTING_CANDIDATES_INIT';
export const GET_VOTING_CANDIDATES_SUCCESS = 'GET_VOTING_CANDIDATES_SUCCESS';
export const GET_VOTING_CANDIDATES_ERROR = 'GET_VOTING_CANDIDATES_ERROR';
