export const GET_ONE_VOTING_INIT = 'GET_ONE_VOTING_INIT';
export const GET_ONE_VOTING_SUCCESS = 'GET_ONE_VOTING_SUCCESS';
export const GET_ONE_VOTING_ERROR = 'GET_ONE_VOTING_ERROR';

export const GET_VOTING_CANDIDATES_INIT = 'GET_VOTING_CANDIDATES_INIT';
export const GET_VOTING_CANDIDATES_SUCCESS = 'GET_VOTING_CANDIDATES_SUCCESS';
export const GET_VOTING_CANDIDATES_ERROR = 'GET_VOTING_CANDIDATES_ERROR';

export const SEND_VOTE_INIT = 'SEND_VOTE_INIT';
export const SEND_VOTE_SUCCESS = 'SEND_VOTE_SUCCESS';
export const SEND_VOTE_ERROR = 'SEND_VOTE_ERROR';

export const CHECK_USER_CAN_VOTE_INIT = 'CHECK_USER_CAN_VOTE_INIT';
export const CHECK_USER_CAN_VOTE_SUCCESS = 'CHECK_USER_CAN_VOTE_SUCCESS';
export const CHECK_USER_CAN_VOTE_ERROR = 'CHECK_USER_CAN_VOTE_ERROR';
