export const GET_VOTING_RESULTS_INIT = 'GET_VOTING_RESULTS_INIT';
export const GET_VOTING_RESULTS_SUCCESS = 'GET_VOTING_RESULTS_SUCCESS';
export const GET_VOTING_RESULTS_ERROR = 'GET_VOTING_RESULTS_ERROR';
