export const CHECK_USER_EXISTS_INIT = 'CHECK_USER_EXISTS_INIT';
export const CHECK_USER_EXISTS_SUCCESS = 'CHECK_USER_EXISTS_SUCCESS';
export const CHECK_USER_EXISTS_ERROR = 'CHECK_USER_EXISTS_ERROR';

export const JOIN_GROUP_INIT = 'JOIN_GROUP_INIT';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_ERROR = 'JOIN_GROUP_ERROR';
