export const GET_AUTH_STAT_INIT = 'GET_AUTH_STAT_INIT';
export const GET_AUTH_STAT_SUCCESS = 'GET_AUTH_STAT_SUCCESS';
export const GET_AUTH_STAT_FAILURE = 'GET_AUTH_STAT_FAILURE';

export const GET_VOTE_STAT_INIT = 'GET_VOTE_STAT_INIT';
export const GET_VOTE_STAT_SUCCESS = 'GET_VOTE_STAT_SUCCESS';
export const GET_VOTE_STAT_FAILURE = 'GET_VOTE_STAT_FAILURE';
